### PR TITLE
106/Fix NPE in TmdbImageUrlProvider

### LINKED ISSUE #106: Kotlin NPE in TmdbImageUrlProvider
On a clean install, getting an NPE where `preview!!` is used in `TmdbImageUrlProvider#selectSize()`. May be fixed via #94.

```sh
01-13 11:56:50.508 5447-5534/me.banes.chris.tivi D/TiviShowDao: Inserting show: TiviShow(id=null, title=The Grand Tour, originalTitle=null, traktId=108999, tmdbId=67557, tmdbPosterPath=null, tmdbBackdropPath=null, lastTraktUpdate=2018-01-13T11:56:50.507Z, lastTmdbUpdate=null, summary=null, homepage=null, rating=null, certification=null, country=null, network=null, runtime=null, _genres=null)
01-13 11:52:39.230 5060-5060/me.banes.chris.tivi E/AndroidRuntime: FATAL EXCEPTION: main
                                                                   Process: me.banes.chris.tivi, PID: 5060
                                                                   kotlin.KotlinNullPointerException
                                                                       at me.banes.chris.tivi.tmdb.TmdbImageUrlProvider.selectSize(TmdbImageUrlProvider.kt:50)
                                                                       at me.banes.chris.tivi.tmdb.TmdbImageUrlProvider.selectSize$default(TmdbImageUrlProvider.kt:31)
                                                                       at me.banes.chris.tivi.tmdb.TmdbImageUrlProvider.getPosterUrl(TmdbImageUrlProvider.kt:26)
                                                                       at me.banes.chris.tivi.ui.databinding.TiviBindingAdaptersKt$loadPoster$1.invoke(TiviBindingAdapters.kt:34)
                                                                       at me.banes.chris.tivi.ui.databinding.TiviBindingAdaptersKt$loadPoster$1.invoke(Unknown Source:2)
                                                                       at me.banes.chris.tivi.extensions.ViewExtensionsKt.doWhenLaidOut(ViewExtensions.kt:45)
                                                                       at me.banes.chris.tivi.ui.databinding.TiviBindingAdaptersKt.loadPoster(TiviBindingAdapters.kt:33)
                                                                       at me.banes.chris.tivi.databinding.ViewHolderPosterGridItemBinding.executeBindings(ViewHolderPosterGridItemBinding.java:284)
                                                                       at android.databinding.ViewDataBinding.executeBindingsInternal(ViewDataBinding.java:379)
                                                                       at android.databinding.ViewDataBinding.executePendingBindings(ViewDataBinding.java:351)
                                                                       at com.airbnb.epoxy.DataBindingEpoxyModel.bind(DataBindingEpoxyModel.java:54)
                                                                       at com.airbnb.epoxy.DataBindingEpoxyModel.bind(DataBindingEpoxyModel.java:34)
                                                                       at com.airbnb.epoxy.EpoxyViewHolder.bind(EpoxyViewHolder.java:54)
                                                                       at com.airbnb.epoxy.BaseEpoxyAdapter.onBindViewHolder(BaseEpoxyAdapter.java:96)
                                                                       at com.airbnb.epoxy.EpoxyControllerAdapter.onBindViewHolder(EpoxyControllerAdapter.java:10)
                                                                       at com.airbnb.epoxy.BaseEpoxyAdapter.onBindViewHolder(BaseEpoxyAdapter.java:14)
                                                                       at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6541)
                                                                       at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5484)
                                                                       at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5750)
                                                                       at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5589)
                                                                       at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5585)
                                                                       at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2231)
                                                                       at android.support.v7.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:556)
                                                                       at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1518)
                                                                       at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:610)
                                                                       at android.support.v7.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:170)
                                                                       at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3719)
                                                                       at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3436)
                                                                       at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3988)
                                                                       at android.view.View.layout(View.java:19590)
                                                                       at android.view.ViewGroup.layout(ViewGroup.java:6053)
                                                                       at android.support.design.widget.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:132)
                                                                       at android.support.design.widget.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:42)
                                                                       at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:1361)
                                                                       at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:874)
                                                                       at android.view.View.layout(View.java:19590)
                                                                       at android.view.ViewGroup.layout(ViewGroup.java:6053)
                                                                       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                       at android.view.View.layout(View.java:19590)
                                                                       at android.view.ViewGroup.layout(ViewGroup.java:6053)
                                                                       at android.support.constraint.ConstraintLayout.onLayout(ConstraintLayout.java:1514)
                                                                       at android.view.View.layout(View.java:19590)
                                                                       at android.view.ViewGroup.layout(ViewGroup.java:6053)
                                                                       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                       at android.view.View.layout(View.java:19590)
                                                                       at android.view.ViewGroup.layout(ViewGroup.java:6053)
01-13 11:52:39.231 5060-5060/me.banes.chris.tivi E/AndroidRuntime:     at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
                                                                       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
                                                                       at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
                                                                       at android.view.View.layout(View.java:19590)
                                                                       at android.view.ViewGroup.layout(ViewGroup.java:6053)
                                                                       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                       at android.view.View.layout(View.java:19590)
                                                                       at android.view.ViewGroup.layout(ViewGroup.java:6053)
                                                                       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
                                                                       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
                                                                       at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
                                                                       at android.view.View.layout(View.java:19590)
                                                                       at android.view.ViewGroup.layout(ViewGroup.java:6053)
                                                                       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                       at com.android.internal.policy.DecorView.onLayout(DecorView.java:758)
                                                                       at android.view.View.layout(View.java:19590)
                                                                       at android.view.ViewGroup.layout(ViewGroup.java:6053)
                                                                       at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2484)
                                                                       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2200)
                                                                       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1386)
                                                                       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6733)
                                                                       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
                                                                       at android.view.Choreographer.doCallbacks(Choreographer.java:723)
                                                                       at android.view.Choreographer.doFrame(Choreographer.java:658)
                                                                       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
                                                                       at android.os.Handler.handleCallback(Handler.java:789)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                       at android.os.Looper.loop(Looper.java:164)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:6541)
                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

### PR DESCRIPTION
**Pull request by ataulm**
This PR fixes #106 the NPE in TmdbImageUrlProvider where `previousUrl` is null but is accessed with `previousUrl!!`.

It also replaces the parsing of the size with regex - I can revert this since this fixes something that will only manifest as a bug if TMDB changes their size format (e.g. from `w72` to `72w` or `w72px`).

### CODE REVIEW

**Comment by ataulm** [comment]
😞 

>#!/bin/bash -eo pipefail
>signing/setup.sh $ENCRYPT_KEY
>aes-256-cbc: Option -k needs a value
>aes-256-cbc: Use -help for summary.
>aes-256-cbc: Option -k needs a value
>aes-256-cbc: Use -help for summary.
>Exited with code 1

File: tmdb/src/main/java/me/banes/chris/tivi/tmdb/TmdbImageUrlProvider.kt [hunk 1]
```diff
@@ -62,4 +55,8 @@ class TmdbImageUrlProvider(
 
         return previousSize ?: sizes.last()
     }
+
+    private fun extractWidthAsIntFrom(size: String): Int? {
+        return "w(\\d+)$".toRegex().matchEntire(size)?.groups?.get(1)?.value?.toInt()
```
Comment (ataulm) [inline tmdb/src/main/java/me/banes/chris/tivi/tmdb/TmdbImageUrlProvider.kt]: - `w` is the literal
- `\d+` is 1 or more instances of a digit
- `$` is end of string, to disallow identifiers like `w100foo`, only accepting format `w100`

would have extracted to a `private static final String` in Java, but not sure of the equivalent in Kotlin 🤔

Comment (christxph) [reply tmdb/src/main/java/me/banes/chris/tivi/tmdb/TmdbImageUrlProvider.kt]: >would have extracted to a private static final String in Java, but not sure of the equivalent in Kotlin 

You could use `private const val PATTERN = "w(\\d+)$"`

Comment (ataulm) [reply tmdb/src/main/java/me/banes/chris/tivi/tmdb/TmdbImageUrlProvider.kt]: perfect thanks! 

commit 9a1617908386639823be731ba45fdc93894de34d
Author: Ataul Munim <hello@ataulm.com>
Date:   Sun Jan 14 12:56:02 2018 +0000

    Extract regex pattern to private const
